<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find sushi_bot_description)/urdf/common.xacro" />

  <xacro:macro name="puma_robot" params="prefix parent *origin">
    <!-- === LINKS === -->

    <!-- base_link -->
    <link name="${prefix}base_link">
      <xacro:default_inertial />
      <visual>
        <origin xyz="0 0 0.15" rpy="0 0 0" />
        <geometry>
          <box size="0.3 0.3 0.3" />
        </geometry>
        <material name="Gazebo/Blue" />
      </visual>
      <collision>
        <origin xyz="0 0 0.15" rpy="0 0 0" />
        <geometry>
          <box size="0.3 0.3 0.3" />
        </geometry>
      </collision>
    </link>

    <!-- Jointed links -->
    <xacro:property name="arm_radius" value="0.05" />
    <xacro:property name="link_len" value="0.4" />

    <link name="${prefix}link1">
      <xacro:default_inertial />
      <visual>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${link_len}" radius="${arm_radius}" />
        </geometry>
        <material name="Gazebo/DarkGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${link_len}" radius="${arm_radius}" />
        </geometry>
      </collision>
    </link>

    <link name="${prefix}link2">
      <xacro:default_inertial />
      <visual>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${link_len}" radius="${arm_radius}" />
        </geometry>
        <material name="Gazebo/Grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${link_len}" radius="${arm_radius}" />
        </geometry>
      </collision>
    </link>

    <link name="${prefix}link3">
      <xacro:default_inertial />
      <visual>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 ${link_len}" />
        </geometry>
        <material name="Gazebo/Red" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link_len/2}" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 ${link_len}" />
        </geometry>
      </collision>
    </link>

    <!-- Wrist links -->
    <link name="${prefix}link4">
      <xacro:default_inertial />
      <visual>
        <geometry>
          <cylinder length="0.1" radius="0.04" />
        </geometry>
        <material name="Gazebo/Yellow" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.1" radius="0.04" />
        </geometry>
      </collision>
    </link>

    <link name="${prefix}link5">
      <xacro:default_inertial />
      <visual>
        <geometry>
          <cylinder length="0.1" radius="0.04" />
        </geometry>
        <material name="Gazebo/Yellow" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.1" radius="0.04" />
        </geometry>
      </collision>
    </link>

    <link name="${prefix}link6">
      <xacro:default_inertial />
      <visual>
        <geometry>
          <cylinder length="0.1" radius="0.03" />
        </geometry>
        <material name="Gazebo/Green" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.1" radius="0.03" />
        </geometry>
      </collision>
    </link>

    <!-- End-effector frames -->
    <link name="${prefix}tool0" />
    <link name="${prefix}flange" />
    <link name="${prefix}base" />

    <!-- === JOINTS === -->

    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${prefix}base_link" />
    </joint>

    <joint name="${prefix}joint1" type="revolute">
      <origin xyz="0 0 0.3" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}link1" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="1000"
        velocity="${radians(180)}" />
    </joint>

    <joint name="${prefix}joint2" type="revolute">
      <origin xyz="0 0 ${link_len}" rpy="0 -${pi/2} 0" />
      <parent link="${prefix}link1" />
      <child link="${prefix}link2" />
      <axis xyz="0 1 0" />
      <limit lower="${radians(-90)}" upper="${radians(90)}" effort="1000" velocity="${radians(180)}" />
    </joint>

    <joint name="${prefix}joint3" type="revolute">
      <origin xyz="0 0 ${link_len}" rpy="0 0 0" />
      <parent link="${prefix}link2" />
      <child link="${prefix}link3" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-90)}" upper="${radians(90)}" effort="1000" velocity="${radians(180)}" />
    </joint>

    <joint name="${prefix}joint4" type="revolute">
      <origin xyz="0 0 ${link_len}" rpy="0 0 0" />
      <parent link="${prefix}link3" />
      <child link="${prefix}link4" />
      <axis xyz="1 0 0" />
      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="1000"
        velocity="${radians(180)}" />
    </joint>

    <joint name="${prefix}joint5" type="revolute">
      <origin xyz="0 0 0.1" rpy="0 0 0" />
      <parent link="${prefix}link4" />
      <child link="${prefix}link5" />
      <axis xyz="0 1 0" />
      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="1000"
        velocity="${radians(180)}" />
    </joint>

    <joint name="${prefix}joint6" type="revolute">
      <origin xyz="0 0 0.1" rpy="0 0 0" />
      <parent link="${prefix}link5" />
      <child link="${prefix}link6" />
      <axis xyz="0 0 1" />
      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="1000"
        velocity="${radians(180)}" />
    </joint>

    <!-- tool0 (end-effector) -->
    <joint name="${prefix}tool_joint" type="fixed">
      <origin xyz="0 0 0.1" rpy="0 ${-pi} ${pi/2}" />
      <parent link="${prefix}link6" />
      <child link="${prefix}tool0" />
    </joint>

    <!-- base and flange references -->
    <joint name="${prefix}base_ref" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}base" />
    </joint>

    <joint name="${prefix}flange_joint" type="fixed">
      <parent link="${prefix}tool0" />
      <child link="${prefix}flange" />
    </joint>
  </xacro:macro>

</robot>
