controller_manager:
  ros__parameters:
    # 制御周期
    update_rate: 100 # Hz

    # コントローラーの名前とタイプを指定
    # - 各名前はコントローラー識別名（後で使う）。
    # - type は対応するクラス（＝プラグイン）のフルネーム。<package>/<controller_class>形式。
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: effort_controllers/JointGroupEffortController

# 各コントローラーの設定
forward_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      # - finger_right_joint
      # - finger_left_joint
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      # - finger_right_joint
      # - finger_left_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz
    action_monitor_rate: 20.0 # Hz

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

gripper_controller:
  ros__parameters:
    joints:
      - finger_right_joint
      - finger_left_joint
